### ISSUE TITLE
Add possibility to edit "free slots" and divide business hours on request

### ISSUE THREAD

**Issue by applicazza** [applicazza/appointed#2]
Example:

The person sets up his business hours 09:00 AM - 02.00 PM, 04:00 PM - 08.00 PM. He has one meeting between 9:30 AM and 10:00 AM and another meeting between 11:00 AM and 11:30 AM. Now he needs a possibility to cancel his business hours from 10:00 AM to 11:00 AM. His business hours must be the following: 09:00 AM - 10.00 PM, 11.00 AM - 02.00 PM, 04:00 PM - 08.00 PM.

**Comment by tusharvikky** [comment]
Any recommended way to get these free slots?
